# Affine Functions with 1 Feature

## Affine Function 

In [20]:
import torch
import torch.nn as nn 
import torch.nn.functional as F
import torch.optim as optim
import torch.utils.data as data
import numpy as np

x = torch.tensor([[10.]]) # input setting
print(x.shape)

class dense(nn.Module): # implementation of an affine function
    def __init__(self, x):
        super().__init__()
        self.out = nn.Linear(1, 1)
        
    def forward(self, x):
        x = self.out(x)
        return x
            

y = dense(x) # forward propagation + parameter initialisation.
w = list(y.parameters()) # get the values of weight, bias

#for p in y.named_parameters():
#    print(p)
    
weight = w[0]
bias = w[1]

res = torch.matmul(x, weight) + bias

print('------- Input/Weight/Bias ----')
print("x: {}\n{}\n".format(x.shape, x.numpy()))
print("w: {}\n{}\n".format(weight.shape, weight))
print("b: {}\n{}\n".format(bias.shape, bias))

print('------Outputs-------')
print('result :', res.item())

torch.Size([1, 1])
------- Input/Weight/Bias ----
x: torch.Size([1, 1])
[[10.]]

w: torch.Size([1, 1])
Parameter containing:
tensor([[0.1549]], requires_grad=True)

b: torch.Size([1])
Parameter containing:
tensor([0.6797], requires_grad=True)

------Outputs-------
result : 2.229147434234619


# Affine Functions with n Features

In [46]:
x = torch.randn(1, 10)
print(x.shape, '\n', x)

class dense(nn.Module): # implementation of an affine function
    def __init__(self, x):
        super().__init__()
        self.out = nn.Linear(x.shape[1], 1)
        
    def forward(self, x):
        x = self.out(x)
        return x
    
    
    
y = dense(x) # forward propagation + parameter initialisation.
w = list(y.parameters()) # get the values of weight, bias


weight = w[0]
print(weight.shape)
bias = w[1]

tmp = torch.transpose(weight, 0, 1)



res = torch.matmul(x, tmp) + bias

print('------- Input/Weight/Bias ----')
print("x: {}\n{}\n".format(x.shape, x.numpy()))
print("w: {}\n{}\n".format(weight.shape, weight))
print("b: {}\n{}\n".format(bias.shape, bias))

print('------Outputs-------')
print('result :', res.item())


torch.Size([1, 10]) 
 tensor([[-0.5020, -1.6458,  0.0757, -2.6537, -0.7118, -1.3015, -1.3694, -1.0865,
         -0.2114,  0.1399]])
torch.Size([1, 10])
------- Input/Weight/Bias ----
x: torch.Size([1, 10])
[[-0.50195575 -1.6458054   0.07569822 -2.6536589  -0.71178687 -1.3014779
  -1.3693922  -1.0865123  -0.21135391  0.13988337]]

w: torch.Size([1, 10])
Parameter containing:
tensor([[-0.0126, -0.1751,  0.1606, -0.0448,  0.1597,  0.1657,  0.1396, -0.3060,
          0.2529, -0.2960]], requires_grad=True)

b: torch.Size([1])
Parameter containing:
tensor([0.2722], requires_grad=True)

------Outputs-------
result : 0.41473355889320374
