# Activation Functions

In [12]:
import torch
import torch.nn as nn 
import torch.nn.functional as F
import torch.optim as optim
import torch.utils.data as data
import numpy as np


x = torch.randn(1, 5)
print(x)

# list of activation functions
sigmoid = nn.Sigmoid()
tanh = nn.Tanh()
relu = nn.ReLU()

# forward propagation(Torch)
y_sig = sigmoid(x)
y_tanh = tanh(x)
y_relu = relu(x)

# implementation on manual
y_sig_impl = 1 / (1 + torch.exp(-x))
y_tanh_impl = (torch.exp(x) - torch.exp(-x)) / (torch.exp(x) + torch.exp(-x))
y_relu_impl = x * (x > 0)


print('Sigmoid(Torch): {}\n{}'.format(y_sig.shape, y_sig.numpy()))
print('Tanh(Torch): {}\n{}'.format(y_tanh.shape, y_tanh.numpy()))
print('ReLU(Torch): {}\n{}'.format(y_relu.shape, y_relu.numpy()))

print('\n-----Implemented Activation Functions Result----')
print('Sigmoid(impl): {}\n{}'.format(y_sig_impl.shape, y_sig_impl.numpy()))
print('Tanh(impl): {}\n{}'.format(y_tanh_impl.shape, y_tanh_impl.numpy()))
print('ReLU(impl): {}\n{}'.format(y_relu_impl.shape, y_relu_impl.numpy()))

tensor([[-0.0255,  1.8212, -0.5620, -0.5810,  2.5007]])
Sigmoid(Torch): torch.Size([1, 5])
[[0.49363673 0.86071575 0.36307925 0.35871354 0.92419386]]
Tanh(Torch): torch.Size([1, 5])
[[-0.02544876  0.9489626  -0.5094777  -0.5233571   0.986634  ]]
ReLU(Torch): torch.Size([1, 5])
[[0.        1.8212472 0.        0.        2.500743 ]]

-----Implemented Activation Functions Result----
Sigmoid(impl): torch.Size([1, 5])
[[0.49363673 0.86071575 0.36307925 0.35871354 0.92419386]]
Tanh(impl): torch.Size([1, 5])
[[-0.02544878  0.9489626  -0.50947773 -0.5233571   0.98663414]]
ReLU(impl): torch.Size([1, 5])
[[-0.         1.8212472 -0.        -0.         2.500743 ]]


## Activation in Dense Layer

In [43]:
x = torch.randn(1, 10)
print(x.shape, '\n', x)

class dense(nn.Module): # implementation of an affine function
    def __init__(self, x):
        super().__init__()
        self.out = nn.Linear(x.shape[1], 1)
        self.sig = nn.Sigmoid()
        
    def forward(self, x):
        x = self.out(x)
        x = self.sig(x)
        return x
    
    
    
y = dense(x) # forward propagation + parameter initialisation.
w = list(y.parameters()) # get the values of weight, bias


weight = w[0]
bias = w[1]

tmp = torch.transpose(weight, 0, 1)



res = torch.matmul(x, tmp) + bias
after_sig = 1 / (1 + torch.exp(-res))



print('------Outputs-------')
print('Result(Torch) :', y(x).item())
print('Result(Impl) :', after_sig.item())



torch.Size([1, 10]) 
 tensor([[ 0.0335, -0.1974,  0.9946,  0.5272,  0.6421, -0.6822, -2.6129,  0.2763,
          0.5373,  1.2876]])
------Outputs-------
Result(Torch) : 0.36683595180511475
Result(Impl) : 0.36683595180511475


In [39]:
x = torch.randn(1, 10)
#print(x.shape, '\n', x)

class dense(nn.Module): 
    def __init__(self, x):
        super(dense, self).__init__()
        self.out = nn.Linear(x.shape[1], 1)
        
    def forward(self, x):
        x = self.out(x)
        return x
    
    

#model= dense(x)
#y = model(x)

y = dense(x)(x)

print(y)

tensor([[0.3609]], grad_fn=<AddmmBackward0>)


# Minibatches

## Shapes of Linear Layer

In [49]:
N, n_features = 8, 10 # set input parameters
x = torch.randn(N, n_features) # generate minibatch
print(x.shape)

class Linear(nn.Module): 
    def __init__(self):
        super(Linear, self).__init__()
        self.out = nn.Linear(10, 1)
        self.relu = nn.ReLU(inplace = True)
        
    def forward(self, x):
        x = self.out(x)
        x = self.relu(x)
        return x
    
model = Linear()
y = model(x)

w = list(model.parameters()) # get the values of weight, bias
weight = w[0]
bias = w[1]

print('Shape of x: {}', x.shape)
print('Shape of w: {}', weight.shape)
print('Shape of b: {}', bias.shape)




torch.Size([8, 10])
Shape of x: {} torch.Size([8, 10])
Shape of w: {} torch.Size([1, 10])
Shape of b: {} torch.Size([1])


## Output Calculation

In [58]:
N, n_features = 8, 10 # set input parameters
x = torch.randn(N, n_features) # generate minibatch

class Linear(nn.Module): 
    def __init__(self):
        super(Linear, self).__init__()
        self.out = nn.Linear(10, 1)
        self.relu = nn.ReLU(inplace = True)
        
    def forward(self, x):
        x = self.out(x)
        x = self.relu(x)
        return x
    
model = Linear()
y = model(x)

w = list(model.parameters()) # get the values of weight, bias
weight = w[0]
bias = w[1]

y_impl = torch.matmul(x, torch.transpose(weight, 0, 1)) + bias
y_impl = y_impl * (y_impl > 0)

print('Result(Torch): ', y.detach().numpy())
print('Result(Impl): ', y_impl)




Result(Torch):  [[0.40047273]
 [0.3695443 ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]]
Result(Impl):  tensor([[0.4005],
        [0.3695],
        [-0.0000],
        [-0.0000],
        [-0.0000],
        [-0.0000],
        [-0.0000],
        [-0.0000]], grad_fn=<MulBackward0>)
