# Conv Layer with Filters

## Shapes with Filters

In [ ]:
import torch
import torch.nn as nn 
import torch.nn.functional as F
import torch.optim as optim
import numpy as np
import matplotlib.pyplot as plt

N, n_H, n_W, n_C = 1, 28, 28, 3
n_filter = 5
k_size = 3

images = torch.rand(N, n_C, n_H, n_W,)
 
class Conv(torch.nn.Module):
    def __init__(self):
        super(Conv, self).__init__()
        self.conv = nn.Conv2d(n_C, n_filter, k_size) # # 합성곱 연산 (입력 채널수 , 출력 채널수, 필터크기, stride=1(defualt))
        
    def forward(self, x):
        x = self.conv(x)
        return x
    
model = Conv()

print("Input Image: {}".format(images.shape))

y = model(images)
w = list(model.parameters()) # get the values of weight, bias

weight = w[0]
bias = w[1]

print("W/B: {} / {}".format(weight.shape, bias.shape))
print("Output Image: {}".format(y.shape))



## Computations with Filters

In [27]:
import torch
import torch.nn as nn 
import torch.nn.functional as F
import torch.optim as optim
import numpy as np
import matplotlib.pyplot as plt

N, n_H, n_W, n_C = 1, 5, 5, 3
n_filter = 3
k_size = 4

images = torch.rand(N, n_C, n_H, n_W,)
 
class Conv(torch.nn.Module):
    def __init__(self):
        super(Conv, self).__init__()
        self.conv = nn.Conv2d(n_C, n_filter, k_size) # # 합성곱 연산 (입력 채널수 , 출력 채널수, 필터크기, stride=1(defualt))
        
    def forward(self, x):
        x = self.conv(x)
        return x

# Forward Propagation (PyTorch)
model = Conv()
y = model(images)
y = y.detach().numpy().squeeze()

#print(y.shape)
print("Output(PyTorch): \n", y)


# Forward Propagation (Manual)
images = images.numpy().squeeze()
#print(images.shape)

w = list(model.parameters()) # get the values of weight, bias

weight = w[0].detach().numpy()
bias = w[1].detach().numpy()

#print(weight.shape, bias.shape)

y_manual = np.zeros(shape = (n_filter, n_H - k_size + 1, n_W - k_size + 1))
for c in range(n_filter):
    c_W = weight[c, : , :, :] # (3 [n_filter], 3 [n_C], 4, 4)
    c_b = bias[c]
    
    #print(c_W.shape, c_b.shape) (3 [n_filter], 3 [n_C], 4, 4)
    for h in range(n_H - k_size + 1):
        for w in range(n_W - k_size + 1):
            window = images[:, h : h + k_size, w : w + k_size]
            #print(window.shape, c_W.shape)
            conv = np.sum(window * c_W) + c_b
            
            y_manual[c, h, w] = conv
            
print("Output(Manual): \n", y_manual)



Output(PyTorch): 
 [[[ 0.0365082   0.2748231 ]
  [-0.18641067 -0.04044719]]

 [[ 0.0192028  -0.03857959]
  [ 0.16839142  0.15484396]]

 [[-0.3403398  -0.2549873 ]
  [-0.16018073 -0.01625764]]]
Output(Manual): 
 [[[ 0.03650818  0.2748231 ]
  [-0.18641062 -0.04044713]]

 [[ 0.01920291 -0.03857952]
  [ 0.16839141  0.15484402]]

 [[-0.34033984 -0.25498742]
  [-0.16018072 -0.01625761]]]


# Conv Layers with Activation Functions

In [29]:
import torch
import torch.nn as nn 
import torch.nn.functional as F
import torch.optim as optim
import numpy as np
import matplotlib.pyplot as plt

N, n_H, n_W, n_C = 1, 5, 5, 3
n_filter = 3
k_size = 4

images = torch.rand(N, n_C, n_H, n_W,)
 
class Conv(torch.nn.Module):
    def __init__(self):
        super(Conv, self).__init__()
        self.conv = nn.Conv2d(n_C, n_filter, k_size) # # 합성곱 연산 (입력 채널수 , 출력 채널수, 필터크기, stride=1(defualt))
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, x):
        x = self.conv(x)
        x = self.sigmoid(x)
        return x

# Forward Propagation (PyTorch)
model = Conv()
y = model(images)
y = y.detach().numpy().squeeze()

#print(y.shape)
print("Output(PyTorch): \n", y)


# Forward Propagation (Manual)
images = images.numpy().squeeze()
#print(images.shape)

w = list(model.parameters()) # get the values of weight, bias

weight = w[0].detach().numpy()
bias = w[1].detach().numpy()

#print(weight.shape, bias.shape)

y_manual = np.zeros(shape = (n_filter, n_H - k_size + 1, n_W - k_size + 1))
for c in range(n_filter):
    c_W = weight[c, : , :, :] # (3 [n_filter], 3 [n_C], 4, 4)
    c_b = bias[c]
    
    #print(c_W.shape, c_b.shape) (3 [n_filter], 3 [n_C], 4, 4)
    for h in range(n_H - k_size + 1):
        for w in range(n_W - k_size + 1):
            window = images[:, h : h + k_size, w : w + k_size]
            #print(window.shape, c_W.shape)
            conv = np.sum(window * c_W) + c_b
            conv = 1 / (1 + np.exp(-conv))
            
            y_manual[c, h, w] = conv
            
print("Output(Manual): \n", y_manual)



Output(PyTorch): 
 [[[0.35038483 0.32333246]
  [0.4253918  0.34190372]]

 [[0.52321285 0.5765016 ]
  [0.5975205  0.52960384]]

 [[0.54823905 0.52039146]
  [0.46832937 0.5865657 ]]]
Output(Manual): 
 [[[0.35038484 0.32333249]
  [0.4253918  0.34190366]]

 [[0.52321281 0.57650161]
  [0.59752048 0.52960383]]

 [[0.54823906 0.52039146]
  [0.46832937 0.58656572]]]
