# Conv Layers

## Shapes of Conv Layers

In [30]:
import torch
import torch.nn as nn 
import torch.nn.functional as F
import torch.optim as optim
import numpy as np
import matplotlib.pyplot as plt

N, n_H, n_W, n_C = 1, 28, 28, 5
n_filter = 10
f_size = 3

images = torch.rand(N, n_C, n_H, n_W,)
 
class Conv(torch.nn.Module):
    def __init__(self):
        super(Conv, self).__init__()
        self.conv = nn.Conv2d(n_C, n_filter, f_size) # # 합성곱 연산 (입력 채널수 1, 출력 채널수 1, 필터크기 28x28 , stride=1(defualt))
        
    def forward(self, x):
        x = self.conv(x)
        return x
    
model = Conv()

y = model(images)
w = list(model.parameters()) # get the values of weight, bias

weight = w[0]
bias = w[1]

print(images.shape)
print(weight.shape)
print(bias.shape)
print(y.shape)

torch.Size([1, 5, 28, 28])
torch.Size([10, 5, 3, 3])
torch.Size([10])
torch.Size([1, 10, 26, 26])


## Correlation Calculation

In [35]:
import torch
import torch.nn as nn 
import torch.nn.functional as F
import torch.optim as optim
import numpy as np
import matplotlib.pyplot as plt

N, n_H, n_W, n_C = 1, 5, 5, 1
n_filter = 1
f_size = 3

images = torch.rand(N, n_C, n_H, n_W,)
 
class Conv(torch.nn.Module):
    def __init__(self):
        super(Conv, self).__init__()
        self.conv = nn.Conv2d(n_C, n_filter, f_size) # # 합성곱 연산 (입력 채널수 1, 출력 채널수 1, 필터크기 28x28 , stride=1(defualt))
        
    def forward(self, x):
        x = self.conv(x)
        return x
    
model = Conv()

y = model(images)
print("Y(Torch): ", y.detach().numpy().squeeze())

w = list(model.parameters()) # get the values of weight, bias

weight = w[0]
bias = w[1]

images = images.numpy().squeeze()
weight = weight.squeeze()
weight = weight.detach().numpy()

print(images.shape)
print(weight.shape)
#print(bias.shape)

y_manual = np.zeros(shape = (n_H - f_size + 1, n_W - f_size + 1))
for i in range(n_H - f_size + 1):
    for j in range(n_W - f_size + 1):
        window = images[i : i + f_size, j : j + f_size]
        y_manual[i, j] = np.sum(window * weight) + bias
        
print("Y(Manual): \n", y_manual)


Y(Torch):  [[0.5396451  0.13605362 0.16865982]
 [0.26625252 0.30295843 0.23418044]
 [0.13633503 0.257427   0.23276612]]
(5, 5)
(3, 3)
Y(Manual): 
 [[0.53964508 0.13605362 0.16865985]
 [0.26625252 0.30295852 0.23418045]
 [0.13633502 0.25742698 0.23276612]]


## Correlation with n-channel

In [38]:
import torch
import torch.nn as nn 
import torch.nn.functional as F
import torch.optim as optim
import numpy as np
import matplotlib.pyplot as plt

N, n_H, n_W, n_C = 1, 5, 5, 3
n_filter = 1
f_size = 3

images = torch.rand(N, n_C, n_H, n_W,)
 
class Conv(torch.nn.Module):
    def __init__(self):
        super(Conv, self).__init__()
        self.conv = nn.Conv2d(n_C, n_filter, f_size) # # 합성곱 연산 (입력 채널수 1, 출력 채널수 1, 필터크기 28x28 , stride=1(defualt))
        
    def forward(self, x):
        x = self.conv(x)
        return x
    
model = Conv()

y = model(images)
print("Y(Torch): ", y.detach().numpy().squeeze())

w = list(model.parameters()) # get the values of weight, bias

weight = w[0]
bias = w[1]

images = images.numpy().squeeze()
weight = weight.squeeze()
weight = weight.detach().numpy()

#print(images.shape)
#print(weight.shape)
#print(bias.shape)

y_manual = np.zeros(shape = (n_H - f_size + 1, n_W - f_size + 1))
for i in range(n_H - f_size + 1):
    for j in range(n_W - f_size + 1):
        window = images[:, i : i + f_size, j : j + f_size]
        #print(window.shape)
        y_manual[i, j] = np.sum(window * weight) + bias
        
print("Y(Manual): \n", y_manual)


Y(Torch):  [[0.5439341  0.49860427 0.34091172]
 [0.5010702  0.49791315 0.6776478 ]
 [0.46009868 0.13545343 0.18529502]]
Y(Manual): 
 [[0.54393411 0.49860421 0.34091175]
 [0.5010702  0.49791315 0.67764777]
 [0.46009874 0.13545345 0.18529497]]
