# Dense Layers

## Shapes of Dense Layers

In [10]:
import torch
import torch.nn as nn 
import torch.nn.functional as F
import torch.optim as optim
import numpy as np


N, n_features = 8, 10
x = torch.randn(N, n_features)

n_neuron = 3

class Dense(torch.nn.Module):
    def __init__(self, n_neuron = 3):
        super(Dense, self).__init__()
        self.layer = nn.Linear(10, n_neuron)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, x):
        x = self.layer(x)
        x = self.sigmoid(x)
        return x
    

model = Dense()
Y = model(x)

w = list(model.parameters()) # get the values of weight, bias
W, B = w[0], w[1]

print('==== Input/Weights/Bias =====')
print('x: ', x.shape)
print('W: ', W.shape)
print('B: ', B.shape)
print('Y: ', Y.shape)

==== Input/Weights/Bias =====
x:  torch.Size([8, 10])
W:  torch.Size([3, 10])
B:  torch.Size([3])
Y:  torch.Size([8, 3])


## Output Calculations

In [11]:
import torch
import torch.nn as nn 
import torch.nn.functional as F
import torch.optim as optim
import numpy as np


N, n_features = 4, 10
x = torch.randn(N, n_features)

n_neuron = 3

class Dense(torch.nn.Module):
    def __init__(self, n_neuron = 3):
        super(Dense, self).__init__()
        self.layer = nn.Linear(10, n_neuron)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, x):
        x = self.layer(x)
        x = self.sigmoid(x)
        return x
    

model = Dense()
Y_torch = model(x)
print('Y(Torch): \n', Y_torch.detach().numpy())

# Calculation with matrix multiplication

w = list(model.parameters()) # get the values of weight, bias
W, B = w[0], w[1]

z = torch.matmul(x, torch.transpose(W, 0, 1)) + B
Y_manual = 1 / (1 + torch.exp(-z))


print('Y(Manual): \n', Y_manual.detach().numpy())

# Calculation with dot products

Y_manual_vec = np.zeros(shape = (N, n_neuron))
for x_idx in range(N):
    x_x = x[x_idx]
    for nu_idx in range(n_neuron):
        w, b = W[nu_idx, :], B[nu_idx] # current W's shape needs to be transposed.
        
        z = torch.sum(x_x * w) + b
        a = 1 / (1 + torch.exp(-z))
        Y_manual_vec[x_idx, nu_idx] = a
        
print('Y(with dot products): \n', Y_manual_vec)

Y(Torch): 
 [[0.6461694  0.35609305 0.45774582]
 [0.49540743 0.4066069  0.548296  ]
 [0.4748421  0.17561656 0.38230848]
 [0.7100764  0.3594805  0.3363649 ]]
Y(Manual): 
 [[0.6461694  0.35609305 0.45774582]
 [0.49540743 0.4066069  0.548296  ]
 [0.4748421  0.17561656 0.38230848]
 [0.7100764  0.35948047 0.3363649 ]]
Y(with dot products): 
 [[0.64616942 0.35609305 0.45774582]
 [0.49540737 0.40660691 0.54829597]
 [0.4748421  0.17561658 0.38230848]
 [0.71007639 0.35948047 0.3363649 ]]


# Cascaded Dense Layers

## Shapes of Cascaded Dense Layers

In [5]:
import torch
import torch.nn as nn 
import torch.nn.functional as F
import torch.optim as optim
import numpy as np

N, n_feature = 4, 10
X = torch.randn(N, n_feature)

n_neurons = [3, 5]

class Dense(torch.nn.Module):
    def __init__(self, n_neurons):
        super(Dense, self).__init__()
        self.layer1 = nn.Linear(10, n_neurons[0])
        self.sigmoid = nn.Sigmoid()  
        self.layer2 = nn.Linear(n_neurons[0], n_neurons[1])

        
    def forward(self, x):
        x = self.layer1(x)
        x = self.sigmoid(x)
        x = self.layer2(x)
        x = self.sigmoid(x)
        return x
    
model = Dense(n_neurons)
y = model(X)

w = list(model.parameters()) # get the values of weight, bias
W1, W2 = w[0], w[2]
B1, B2 = w[1], w[3]

print('Shape of W1: ', W1.shape)
print('Shape of B1: ', B1.shape)
print('Shape of W2: ', W2.shape)
print('Shape of B2: ', B2.shape)



Shape of W1:  torch.Size([3, 10])
Shape of B1:  torch.Size([3])
Shape of W2:  torch.Size([5, 3])
Shape of B2:  torch.Size([5])


## Output Calculations

In [9]:
import torch
import torch.nn as nn 
import torch.nn.functional as F
import torch.optim as optim
import numpy as np

N, n_feature = 4, 10
X = torch.randn(N, n_feature)

n_neurons = [3, 5]

class Dense(torch.nn.Module):
    def __init__(self, n_neurons):
        super(Dense, self).__init__()
        self.layer1 = nn.Linear(10, n_neurons[0])
        self.sigmoid = nn.Sigmoid()  
        self.layer2 = nn.Linear(n_neurons[0], n_neurons[1])

        
    def forward(self, x):
        x = self.layer1(x)
        x = self.sigmoid(x)
        x = self.layer2(x)
        x = self.sigmoid(x)
        return x
    
model = Dense(n_neurons)
Y = model(X)
print('Y(Torch): \n', Y.detach().numpy())



w = list(model.parameters()) # get the values of weight, bias
W1, W2 = w[0], w[2] # 3 x 10, 5 x 3
B1, B2 = w[1], w[3] # 1 x 3, 1 x 5

z1 = torch.matmul(X, torch.transpose(W1, 0, 1)) + B1 # 4 x 3
a1 = 1 / (1 + torch.exp(-z1))
z2 = torch.matmul(a1, torch.transpose(W2, 0, 1)) + B2
Y_manual = 1 / (1 + torch.exp(-z2))

    
print('\nY(Manual): ', Y_manual.detach().numpy())


Y(Torch): 
 [[0.590078   0.531353   0.40341693 0.2722073  0.32825536]
 [0.58798844 0.54451716 0.4135065  0.3291468  0.3706317 ]
 [0.6203747  0.5452508  0.42362025 0.27643445 0.3312044 ]
 [0.6067483  0.53530705 0.39559206 0.2632394  0.3265294 ]]

Y(Manual):  [[0.590078   0.531353   0.40341693 0.2722073  0.32825536]
 [0.58798844 0.54451716 0.4135065  0.3291468  0.3706317 ]
 [0.6203747  0.5452508  0.42362025 0.27643445 0.3312044 ]
 [0.6067483  0.53530705 0.39559206 0.2632394  0.3265294 ]]
