# Pooling

## Max Pooling

In [29]:
import torch
import torch.nn as nn 
import torch.nn.functional as F
import torch.optim as optim
import numpy as np
import matplotlib.pyplot as plt

N, n_H, n_W, n_C = 1, 5, 5, 3
f, s = 2, 2

x = torch.randn(N, n_C, n_H, n_W)

pool_max = nn.MaxPool2d(f, s)
pooled_max = pool_max(x)

#print("x: {}\n{}".format(x.shape, x.detach().numpy().flatten()))
print("\npooled_max(Torch): {}\n{}".format(pooled_max.shape, pooled_max.detach().numpy()))

x = x.detach().numpy().squeeze()
n_H_ = np.floor((n_H - f) / s + 1 ).astype(int)
n_W_ = np.floor((n_W - f) / s + 1 ).astype(int)

#print(n_C, n_H, n_W) # 3, 2, 2

pooled_max_manual = np.zeros(shape = (n_C, n_H_, n_W_))
for c in range(n_C):
    c_image = x[c, :, :]
    
    h_ = 0 
    for h in range(0, n_H - f + 1, s):
        w_ = 0
        for w in range(0, n_W - f + 1, s):
            window = c_image[h : h + f, w : w + f]
            pooled_max_manual[c, h_, w_] = np.max(window)
            #print(c, h, w)
            w_ += 1
            
        h_ += 1
        

print("pooled_max(Manual): {} \n {}".format(pooled_max_manual.shape, pooled_max_manual))
        


pooled_max(Torch): torch.Size([1, 3, 2, 2])
[[[[0.82529014 1.3897359 ]
   [0.6511884  0.3213265 ]]

  [[1.0981916  2.0139306 ]
   [0.31490722 0.3781145 ]]

  [[0.7874302  0.08493886]
   [0.326717   1.4697682 ]]]]
pooled_max(Manual): (3, 2, 2) 
 [[[0.82529014 1.38973594]
  [0.65118837 0.32132649]]

 [[1.09819162 2.01393056]
  [0.31490722 0.37811449]]

 [[0.78743023 0.08493886]
  [0.32671699 1.46976817]]]


# Padding

## ZeroPadding2D Layer

In [31]:
import torch
import torch.nn as nn 
import torch.nn.functional as F
import torch.optim as optim
import numpy as np
import matplotlib.pyplot as plt

images = torch.randn(1, 3, 28, 28)
print(images.shape)

zero_padding = nn.ZeroPad2d(2)
y = zero_padding(images)
print(y.shape)

torch.Size([1, 3, 28, 28])
torch.Size([1, 3, 32, 32])
